apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "uwajima.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"  # Set task start time in UTC time zone ( Every Day )
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "uwajima.serviceAccountName" . }}
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - name: http
                containerPort: 80
                protocol: TCP
            livenessProbe:
              failureThreshold: 5
              httpGet:
                path: /health
                port: http
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 5
            readinessProbe:
              failureThreshold: 5
              httpGet:
                path: /health
                port: http
                scheme: HTTP
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 5
            envFrom:
              - configMapRef:
                  name: {{ .Chart.Name }}-env
                  
